-- MySQL Script generated by MySQL Workbench
-- ter 17 mai 2022 21:01:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eventos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eventos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventos` DEFAULT CHARACTER SET utf8 ;
USE `eventos` ;

-- -----------------------------------------------------
-- Table `eventos`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  `imagem` VARCHAR(45) NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`submissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`submissoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `eventos_id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `resumo` TEXT NULL,
  `arquivo` VARCHAR(45) NULL,
  `tipo` CHAR(1) NULL,
  `aceito` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_submissoes_eventos_idx` (`eventos_id` ASC) VISIBLE,
  CONSTRAINT `fk_submissoes_eventos`
    FOREIGN KEY (`eventos_id`)
    REFERENCES `eventos`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`submissoes_has_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`submissoes_has_usuarios` (
  `submissoes_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`submissoes_id`, `usuarios_id`),
  INDEX `fk_submissoes_has_usuarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_submissoes_has_usuarios_submissoes1_idx` (`submissoes_id` ASC) VISIBLE,
  CONSTRAINT `fk_submissoes_has_usuarios_submissoes1`
    FOREIGN KEY (`submissoes_id`)
    REFERENCES `eventos`.`submissoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_submissoes_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `eventos`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`inscricoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`inscricoes` (
  `eventos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`eventos_id`, `usuarios_id`),
  INDEX `fk_eventos_has_usuarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_eventos_has_usuarios_eventos1_idx` (`eventos_id` ASC) VISIBLE,
  CONSTRAINT `fk_eventos_has_usuarios_eventos1`
    FOREIGN KEY (`eventos_id`)
    REFERENCES `eventos`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `eventos`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
 
